language : php
php:
  - 7.1
  - 7.2
install:
  - composer selfupdate
  - composer install

script:
  - ./vendor/bin/phpcs -s
  - ./vendor/bin/php-cs-fixer fix --diff --dry-run
  - ./vendor/bin/phpunit --colors
